# Generated by Django 4.0.2 on 2022-05-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitysn_app', '0003_post_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post/%Y/%m'),
        ),
    ]
