# Generated by Django 4.0.2 on 2022-05-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitysn_app', '0005_user_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
