# Generated by Django 4.0.2 on 2022-05-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitysn_app', '0009_remove_post_image_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/comment/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='image',
            field=models.ImageField(null=True, upload_to='static/reply/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='static/user/%Y/%m'),
        ),
    ]
