# Generated by Django 4.0.2 on 2022-05-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitysn_app', '0012_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/post/%Y/%m'),
        ),
    ]
