# Generated by Django 4.0.2 on 2022-05-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitysn_app', '0013_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='image',
            field=models.ImageField(null=True, upload_to='reply/%Y/%m'),
        ),
    ]
