# Generated by Django 4.0.2 on 2022-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitysn_app', '0020_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='is_win',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reply/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/user/%Y/%m'),
        ),
    ]
