# Generated by Django 4.0.2 on 2022-05-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitysn_app', '0021_alter_bid_is_win_alter_reply_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(null=True, upload_to='comment/%Y/%m'),
        ),
    ]
