# Generated by Django 4.0.2 on 2022-05-23 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charitysn_app', '0023_remove_comment_image_like_created_date_like_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='like',
            name='types',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='report',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
